--PagoPrestamoDebitoCuenta
INSERT INTO COMPONENT(ID_COMPONENT,NAME,DESCRIPTION) VALUES(14, 'ConsultaProductos', 'Consulta Productos');
--PagoPrestamoDebitoCuenta
INSERT INTO PARAMETER(ID_COMPONENT,NAME,VALUE) VALUES(14, 'HOST', 'http://10.96.36.224:7877/ProductosServicios/SaldoCuenta/service');
INSERT INTO PARAMETER(ID_COMPONENT,NAME,VALUE) VALUES(14, 'CANAL_PRESTAMOS', 'ATM');
INSERT INTO PARAMETER(ID_COMPONENT,NAME,VALUE) VALUES(14, 'TIPOCUENTATARJETA', 'Tarjeta de Credito Local');
INSERT INTO PARAMETER(ID_COMPONENT,NAME,VALUE) VALUES(14, 'TIPOCUENTAPRESTAMO', 'Prestamo');
INSERT INTO PARAMETER(ID_COMPONENT,NAME,VALUE) VALUES(14, 'MONEDALOCAL', 'DOP');